<div class="content_left">
<?php echo base_url; 
$result1 = $this->get('result1');    
		if ($result1)

{
echo "<p>Запрос на выборку данных из базы не прошел. Напишите об этом администратору<br> <strong>Код ошибки:</strong></p>";

}
			while ($row = mysqli_fetch_array($result1)) {
				?>

				<div class="sidebar2">
					<h1><a href="<?php echo base_url . 'metodrecommendations/teacher?articles&id='.$row['id']; ?>"><?php echo $row['title']."<br/>"; ?></a></h1>
					<p><?php $text = $row['text'];
					$counttext = 1000;
					$text = substr($text, 0, $counttext);
					$text = rtrim($text);
					$text = substr($text, 0, strrpos($text, ' '));
					if (mb_strlen($row['text']) > $counttext) {
						echo $text; 
						echo "<a href=".base_url . 'metodrecommendations/teacher?articles&id='.$row['id']."> Читати далі . . .</a>";
					} else {
						echo $row['text'];
					}	?></p>	<br/>		
					<i class="far fa-clock"></i> <?php echo $row['date'];?> / <?php echo $row['time']; ?>
					<span class="author"><i class="fas fa-user-edit"></i><?php echo $row['author']."<br/>"; ?></span>
					<br/>
					
				</div>

				<?php     
			}
?>
</div>
