
	<?php 



	// Ограничиваем количество ссылок, которые будут выводиться перед и
// после текущей страницы
		$limit=3;

		$page = $this->get('page');
		$pages = $this->get('pages');	
		$num = $this->get('num');
		$quantity = $this->get('quantity');
		$result1 = $this->get('result1');

			while ($row = mysqli_fetch_array($result1)) {
				?>

				
					<h1><a href="<?php echo base_url . 'metodrecommendations/teacher?articles&id='.$row['id']; ?>"><?php echo $row['title']."<br/>"; ?></a></h1>
					<p><?php $text = $row['text'];
					$counttext = 1000;
					$text = substr($text, 0, $counttext);
					$text = rtrim($text);
					$text = substr($text, 0, strrpos($text, ' '));
					if (mb_strlen($row['text']) > $counttext) {
						echo $text; 
						echo "<a href=".base_url . 'metodrecommendations/teacher?articles&id='.$row['id']."> Читати далі . . .</a>";
					} else {
						echo $row['text'];
					}	?></p>	<br/>		
					<p>Дата публікації: <?php echo $row['date'];?> / <?php echo $row['time']; ?>
						<span class="author">Автор: <?php echo $row['author']."<br/>"; ?></span>
					</p><br/>
					<a class="a-left delete" href="<?php echo base_url . 'metodrecommendations/teacher?delete&id='.$row['id']; ?>"><i class="fas fa-trash-alt"></i>Видалити</a>
					<a class="a-left edit" href="<?php echo base_url . 'metodrecommendations/teacher?edit&id='.$row['id']; ?>"><i class="fas fa-pencil-alt"></i>Редагувати</a>
					
				

				<?php }     
			
			
		

		?>
	
fafregrsegs



				