			
<div class="sidebar_right">



	<div class="sidebar">
		<h2><i class="fas fa-puzzle-piece"></i>Розділи</h2>
		<ul>
			<li><a href="<?php echo base_url . 'index'; ?>">Головна</a>
			<li><a href="<?php echo base_url . 'metodrecommendations'; ?>">Методичні рекомендації</a>
				<ul>
					<li><a href="<?php echo base_url . 'metodrecommendations/teacher'; ?>">Викладачу</a></li>
					<li><a href="<?php echo base_url . 'metodrecommendations/master'; ?>">Майстру в/н</a></li>
					<li><a href="<?php echo base_url . 'metodrecommendations/chairman_mk'; ?>">Голові МК</a></li>
					<li><a href="<?php echo base_url . 'metodrecommendations/young_teacher'; ?>">Молодому педагогу</a></li>
					<li><a href="<?php echo base_url . 'metodrecommendations/class_teacher'; ?>">Класному керівнику</a></li>
				</ul>
			</li>
			<li><a href="<?php echo base_url . 'attestation'; ?>">Атестація</a></li>
			<li><a href="<?php echo base_url . 'qualifications'; ?>">Підвищення кваліфікації</a></li>
			<li><a href="<?php echo base_url . 'internship'; ?>">Стажування</a></li>
			<li><a href="<?php echo base_url . 'pedagogical_experience'; ?>">Поширення педагогічного досвіду</a></li>
			<li><a href="<?php echo base_url . 'news'; ?>">Новини</a></li>		
		</ul>
		

	</div>
</div>
