<div class="stcnt">
	<div class="content_left">
		<div class="sidebar1">
			<div class="contact">
				<h2>Контакти</h2>
				<span class="s-left tooltipcon" data-title="vpu.metodist@ukr.net"><i class="fas fa-envelope"></i>Пишіть нам</span>
				<span class="s-left tooltipcon con" data-title="Вул. Цілковського"><i class="fas fa-map-marker"></i>Приїжайте до нас</span>
				<div id="map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4557.158948325127!2d26.7451893629763!3d50.99879926103095!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4728cb9ca72e6fff%3A0x5b5693e824be2365!2z0JHQtdGA0LXQt9C90LUsINCg0ZbQstC90LXQvdGB0YzQutCwINC-0LHQu9Cw0YHRgtGMLCAzNDYwMA!5e1!3m2!1suk!2sua!4v1526413418620" width="100%" height="450" frameborder="0" style="border:0; margin-top: 40px; border-radius: 5px;" allowfullscreen></iframe></div>
				<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBozNgjfuSei-2SF-LDoeHm2Yomo1qReIM&callback=initMap">
    </script>
			</div>
		</div>
	</div>
</div>