<div class="stcnt">
	<div class="content_left">
		<div class="sidebar1">
			<div class="contact">
				<h2>Контакти</h2>
				<span class="s-left tooltipcon" data-title="vpu.metodist@ukr.net"><i class="fas fa-envelope"></i>Пишіть нам</span>
				<span class="s-left tooltipcon con" data-title="Вул. Цілковського, 2"><i class="fas fa-map-marker"></i>Приїжайте до нас</span>
				<div id="map">
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2510.962072491081!2d26.738743015469822!3d50.99837300561376!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4728cb0b2d39a325%3A0x9dfd9532f6a7faaf!2z0JHQtdGA0LXQt9C90ZbQstGB0YzQutC1INCS0J_Qow!5e0!3m2!1suk!2sua!4v1526563048914" width="100%" height="450" frameborder="0" style="border:0; margin-top: 40px; border-radius: 5px;" allowfullscreen></iframe></div>
					<script async defer
					src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBozNgjfuSei-2SF-LDoeHm2Yomo1qReIM&callback=initMap">
				</script>
			</div>
		</div>
	</div>
</div>