		<div class="footer">
			<div class="footcontent">
				<div class="footcontent_size">
					<div class="footcontent_left">
						<h2>Про нас</h2>
						<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius llorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam. </p>
					</div>
					<div class="footcontent_right">
						<h2>Надихайтеся</h2>
						<ul>	
							<li>Не забувайте тих, хто допоміг вам піднятися!</li><br/>
							<li>Щоб щось мати, потрібно щось зробити!</li><br/>
						
							<li>Ніхто не змусить тебе так, як ти сам!</li><br/>
							<li>Зробіть себе в першу чергу!</li><br/>
							<li>Ваш час - ваше життя!</li>
						</ul>
					</div>
				</div>

			</div>
		<div class="fot_bottom">
			<div class="footer_left">
				<div class="fotleft">
					Є якісь пропозиції, пишіть нам на пошту. </br>
					<a href="#">vpu.metodist@ukr.net</a>
				</div>			
			</div>
			
			<div class="footer_center">
				<div class="fotcenter">
					&copy;Copyright MyWebSite</br>
				Копіювання сайта заборонено! 
				</div>
			</div>
			
			<div class="footer_right">
				<div class="fotright">
					Designed by Blue. </br>
					Чекаємо ваших пропозицій.
				</div>
			</div>
		</div>	
	</div>
