		<div class="footer">
			<div class="footer_left">
				<div class="fotleft">
					Є якісь пропозиції, пишіть нам на пошту. </br>
					<a href="#">vpu.metodist@ukr.net</a>
				</div>			
			</div>
			
			<div class="footer_center">
				<div class="fotcenter">
					&copy;Леся Булавіна</br>
				Копіювання сайта заборонено! 
				</div>
			</div>
			
			<div class="footer_right">
				<div class="fotright">
					Допоможіть розробці сайта. </br>
					Чекаємо ваших пропозицій.
				</div>
			</div>
		</div>	

