		<div class="footer">
			<div class="footcontent">
				<div class="footcontent_size">
					<div class="footcontent_left">
						<h2>Про нас</h2>

						<p><img src="<?php echo base_url . 'img/about.png'; ?>" alt="Наша емблема" class="img_about">    Методична служба ДПТНЗ "Березнівське ВПУ" налічує 53 педагогічних працівників, які прагнуть працювати на випередження, щоб бути конкурентноспроможними. Наші педагоги опрацьовують та впроваджують сучасні освітні і виробничі технології, володіють передовими методами проведення навчальних заннять. Їх форми роботи Ви можете переглянути на нашому сайті!  </p>
					</div>
					<div class="footcontent_right">
						<h2>Надихайтеся</h2>
						<i>
						<ul>	
							<li>Не забувайте тих, хто допоміг вам піднятися!</li><br/>
							<li>Щоб щось мати, потрібно щось зробити!</li><br/>
						
							<li>Ніхто не змусить тебе так, як ти сам!</li><br/>
							<li>Зробіть себе в першу чергу!</li><br/>
							<li>Ваш час - ваше життя!</li>
						</ul></i>
					</div>
				</div>

			</div>
		<div class="fot_bottom">
			<div class="footer_left">
				<div class="fotleft">
					Є якісь пропозиції, пишіть нам на пошту. </br>
					<a href="#">vpu.metodist@ukr.net</a>
				</div>			
			</div>
			
			<div class="footer_center">
				<div class="fotcenter">
					&copy;Copyright MyWebSite</br>
				Копіювання сайта заборонено! 
				</div>
			</div>
			
			<div class="footer_right">
				<div class="fotright">
					Помітили помилку? </br>
					Повідомте про це <a href="#">ССИЛКА</a>
				</div>
			</div>
		</div>	
	</div>
