		<div class="header">
			<div class="logo">
				<div class="logo_text">
					<h1><a href="/"><img src="<?php echo base_url . 'img/logo.png'; ?>" alt="Мастерица"></a></h1>
					<h2>Пізнавай разом з нами!</h2>
				</div>
				
				<div class="menubar">
					<ul class="menu">
						<li class="golovna"><a href="/index">Головна</a></li>
						<li><a href="/maystru">Майстру</a></li>
						<li><a href="/vukladachy">Викладачу</a></li>
						<li><a href="#">Контакти</a></li>
					</ul>
				</div>
			</div>

		</div>