			<head>
			<link rel="shortcut icon" href="img/x-icon.png" type="image/x-icon">
	<link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/menu.css">
	<link rel="stylesheet" href="css/site_content.css">
	<link rel="stylesheet" href="css/footer.css">
</head>

		<div class="header">
			<div class="logo">
				<div class="logo_text">
					<h1><a href="#"><img src="img/logo.png" alt="Мастерица"></a></h1>
					<h2>Пізнавай разом з нами!</h2>
				</div>
				
				<div class="menubar">
					<ul class="menu">
						<li class="golovna"><a href="#">Головна</a></li>
						<li><a href="#">Каталог</a></li>
						<li><a href="#">Контакти</a></li>
					</ul>
				</div>
			</div>

		</div>