<!DOCTYPE html>
<html lang="ua">
    <head>
        <title>{{$title}}</title>
        <meta name="title" content="{{$title}}" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        {{$headfiles}}
        <link rel="shortcut icon" href="<?php echo base_url . 'img/x-icon.png'; ?>" type="image/x-icon">
     </head>
    <body>
        {{$header}}
        <div class="side_content">
        {{$rightblock}}
        {{$content}}
        </div>
        {{$footer}}
    </body>
</html>