<html doctype="html">
    <head>
        <title>{{$title}}</title>
        <meta name="title" content="{{$title}}" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        {{$headfiles}}
        <link rel="shortcut icon" href="img/x-icon.png" type="image/x-icon">
        <link href="styles/footer.css" type="text/css" rel="stylesheet">
     </head>
    <body>
        {{$header}}
        {{$rightblock}}
         <!-- контент сюда попадает из файла , которий засетан в текущем контролере - например $template->setFile('templates/main.phtml') -->
       <div class="content"> {{$content}} </div>
        {{$footer}}
    </body>
</html>