<div class="stcnt">
	<div class="content_left">
				
		<div class="sidebar1">
			<h2>Основна робота методиста – допомогти вчителю розкрити свої таланти.</h2>
				<p>
					Якість та результати навчально-виховного процесу школи залежать передусім від учителя, його теоретичної підготовки, педагогічної та методичної майстерності. Підвищенню фахової підготовки педагогічних працівників у школах сприяє спеціальна методична робота, яка дає змогу молодим учителям оволодівати педагогічною майстерністю, ознайомлюватися з досягненнями психолого-педагогічних дисциплін і методик їх викладання, вивчати і впроваджувати передовий педагогічний досвід, вдосконалювати навички самоосвітньої роботи. Вона забезпечує надання вчителю кваліфікованої допомоги з теорії та практичної діяльності.
				</p>
		</div> 
		<div class="sidebar1">
			<h2>У чому полягає основна робота методиста?</h2>

				<p>Основна робота методиста – це допомогти вчителю розкрити свої таланти, надати йому кваліфікаційну допомогу як у питаннях теорії, так і в практичній діяльності у підвищенні результативності його педагогічної праці.</p>

				<p>З метою підвищення професійної кваліфікації та методичної майстерності педагог проходить атестацію, під час якої він розказує про свою лабораторію, показує як проводить уроки, ділиться своїм напрацьованим досвідом з іншими вчителями. І якраз методкабінет має допомогти вчителю, підтримати його, не відбити у нього бажання працювати в школі. Атестація має бути святом для вчителя, а не покаранням. Треба підтримувати людину, якщо ви бачите, що вона дійсно старається і хоче працювати з дітьми. Я «відкрила» дуже багатьох талановитих вчителів.</p>
		</div>
	<!-- <div class="container">
		<h1>Галерея</h1>
		<div id="galery">
			<figure class="photo"><a data-lightbox="roadtrip" href="img/originals/img-01.jpg"><img src="img/img-01-min.jpg" alt=""></a>
						<figcaption>Орел</figcaption>
					</img></figure>
			<figure class="photo"><a data-lightbox="roadtrip" href="img/originals/img-02.jpg"><img src="img/img-02-min.jpg" alt=""></a>
						<figcaption>Паста</figcaption>
					</img></figure>
			<figure class="photo"><a data-lightbox="roadtrip" href="img/originals/img-03.jpg"><img src="img/img-03-min.jpg" alt=""></a>
						<figcaption>Гарбузи</figcaption>
					</img></figure>
			<figure class="photo"><a data-lightbox="roadtrip" href="img/originals/img-04.jpg"><img src="img/img-04-min.jpg" alt=""></a>
						<figcaption>Ягоди</figcaption>
					</img></figure>
			<figure class="photo"><a data-lightbox="roadtrip" href="img/originals/img-05.jpg"><img src="img/img-05-min.jpg" alt=""></a>
						<figcaption>Природа</figcaption>
					</img></figure>
			<figure class="photo"><a data-lightbox="roadtrip" href="img/originals/img-06.jpg"><img src="img/img-06-min.jpg" alt=""></a>
						<figcaption>Страва</figcaption>
					</img></figure>
			<figure class="photo"><a data-lightbox="roadtrip" href="img/originals/img-07.jpg"><img src="img/img-07-min.jpg" alt=""></a>
						<figcaption>Ніч</figcaption>
					</img></figure>
			<figure class="photo"><a data-lightbox="roadtrip" href="img/originals/img-08.jpg"><img src="img/img-08-min.jpg" alt=""></a>
						<figcaption>Виноград</figcaption>
					</img></figure>
			<figure class="photo"><a data-lightbox="roadtrip" href="img/originals/img-09.jpg"><img src="img/img-09-min.jpg" alt=""></a>
						<figcaption>Захід</figcaption>
					</img></figure> -->
			</div>
		</div>		
	</div>	
</div>