			
<div class="sidebar_right">

		<div class="sidebar">
		<?php 
		if (!isset($_SESSION['email'])) { ?>	
		<div class="lables">
			<span><a href="<?php echo base_url . 'user/login'; ?>">Увійти</a></span> | <span><a href="<?php echo base_url . '/user/registration'; ?>">Реєстрація</a></span>
		</div>

		<?php }
		else {
			echo 'Ви увійшли, як '.$_SESSION['email']; ?>
			<br/>
			<a href="<?php echo base_url .'user/logout'; ?>">Вийти</a>
		<?php }
		?>					
	</div>

	<div class="sidebar">

		<h2><img src="<?php echo base_url . 'img/lupa.png'; ?>" alt="">  Пошук</h2>
		<form action="#" method="post">
			<input type="search" id="search_form" placeholder=" ваш запит" />
			<input type="submit" class="btn" value="знайти" />
		</form>

	</div>

	<div class="sidebar">
		<h2>Для вас шановні</h2>
		<a href="/qualifications">Підвищення кваліфікації</a></br>
		<a href="/internship">Стажування</a></br>
		<a href="/pedagogical_experience">Поширення педагогічного досвіду</a>

	</div>
	<div class="sidebar">
		<h2>Новини</h2>
		<a href="#">Добавили пошук на сайті.</a></br>
		<a href="#">Нові вироби учнів.</a></br>
		<a href="#">Скоро з'явиться реєстрація.</a>
	</div>
</div>
