<div class="content_left">
	<?php 
	$search_query = $this->get('search_query');
	$num = $this->get('num');
	$query = $this->get('query');
	$search_error = $this->get('search_error');
	if (!empty($search_error)) { ?>
	<div class="sidebar_error">
		<span style="color:white;"><?php echo $search_error; ?></span> 
	</div>
	<?php } ?>
	<div class="sidebar2 search">
		<h2>Пошук</h2>
		<form action="/search" method="get">
			<input type="search" name="search_query" id="search_form" placeholder=" ваш запит" value="<?php echo @$_GET['search_query']; ?>" minlength="4"/ required>
			<input type="submit" name="search" class="btn" value="знайти" /><br/><br/>
			<input type="checkbox" id="allwords" name="allwords" value=" AND " />
			<label for="allwords">Точний збіг всіх слів</label>
		</form>
		<?php
	if ($num != 0 && !empty($search_query)) {
		
		echo '<br/><p style="color:green;">За запитом <b>"'. $search_query.'"</b> знайдено збігів: '.$num.'</p>';
		} ?>	
	</div>
	<?php
$query1 = 'SELECT * FROM `master` WHERE $query_search';
	if ($num != 0 && !empty($search_query)) {
		while ($row = mysqli_fetch_array($query)) { ?>
		<div class="sidebar2">
			<h1><a href="<?php echo base_url;
			if ($query == $query1) {
			echo 'metodrecommendations/master';
		}
			echo '?articles&id='.$row['id']; ?>"><?php echo $row['title']."<br/>"; ?></a></h1>
			<p><?php $text = $row['text'];
			$counttext = 1000;
			$text = substr($text, 0, $counttext);
			$text = rtrim($text);
			$text = substr($text, 0, strrpos($text, ' '));
			if (mb_strlen($row['text']) > $counttext) {
				echo $text; 
				echo "<a href=".base_url . 'news?articles&id='.$row['id']."> Читати далі . . .</a>";
			} else {
				echo $row['text'];
			}	?></p>	<br/>		
			<p>Дата публікації: <?php echo $row['date'];?> / <?php echo $row['time']; ?>
				<span class="author">Автор: <?php echo $row['author']."<br/>"; ?></span>
			</p><br/>

		</div>
		<?php }
	} 

	?>

	
</div>