	<?php 
	$result = $this->get('result');	
	while ($row = mysqli_fetch_array($result)) {
		?>
		<div class="content_left">
			<div class="sidebar2">
				<h1><?php echo $row['title']."<br/>"; ?></h1>
				<p><?php echo $row['text']."<br/>"; ?></p>
				<br/>
				<span>Дата публікації: <?php echo $row['date'];?> / <?php echo $row['time']; ?>
					<span class="author">Опублікував: <?php echo $row['author']."<br/>"; ?></span>
				</span>
				<a href="edit.php?id=<?php echo $row['id'] ?>">Редактировать новость</a>
				<a class="author" href="delete.php?id=<?php echo $row['id'] ?>">Удалить новость</a>
			</div>
		</div>	

		<?php } 
		?>
