<div class="content_left">
	<?php 
	// Ограничиваем количество ссылок, которые будут выводиться перед и
// после текущей страницы
	$limit=3;

	$page = $this->get('page');
	$pages = $this->get('pages');	
	$num = $this->get('num');
	$quantity = $this->get('quantity');

	if ($num > $quantity) {
		echo '<strong style="color: #000; float:right; padding-right: 20px;">Сторінка № ' . $page .'</strong><br /><br />';
	}	

	$num_result = $this->get('num_result');	
	$result1 = $this->get('result1');    
	for ($i = 0; $i<$num_result; $i++) {
		while ($row = mysqli_fetch_array($result1)) {
			?>

			<div class="sidebar2">
				<h1><a href="#"><?php echo $row['title']."<br/>"; ?></a></h1>
				<p><?php echo $row['text']."<br/>"; ?></p>
				<p>Дата публікації: <?php echo $row['date'];?> / <?php echo $row['time']; ?>
					<span class="author">Автор новини: <?php echo $row['author']."<br/>"; ?></span>
				</p>
			</div>
		
			<?php }     
		}
		if ($num > $quantity) {
			

		// Выводим ссылки "назад" и "на первую страницу"
			if ($page>=1) {

    // Значение page= для первой страницы всегда равно единице, 
    // поэтому так и пишем
				echo '<span class="page_center"><a class="page" href="'.base_url . 'metodrecommendations/teacher?page=1"><<</a> &nbsp; ';

    // Так как мы количество страниц до этого уменьшили на единицу, 
    // то для того, чтобы попасть на предыдущую страницу, 
    // нам не нужно ничего вычислять
				echo '<a class="page" href="' .base_url . 'metodrecommendations/teacher?page=' . $page . 
				'">< </a> &nbsp; ';
			}

        // На данном этапе номер текущей страницы = $page+1
			$this1 = $page+1;

// Узнаем с какой ссылки начинать вывод
			$start = $this1-$limit;

// Узнаем номер последней ссылки для вывода
			$end = $this1+$limit;

// Выводим ссылки на все страницы
// Начальное число $j в нашем случае должно равнятся единице, а не нулю
			for ($j = 1; $j<$pages; $j++) {

    // Выводим ссылки только в том случае, если их номер больше или равен
    // начальному значению, и меньше или равен конечному значению
				if ($j>=$start && $j<=$end) {

        // Ссылка на текущую страницу выделяется жирным
					if ($j==($page)) echo '	<a class="page_active" href="'.base_url . 'metodrecommendations/teacher?page=' . $j . '"><strong>' . $j . 
						'</strong></a> &nbsp; ';

        // Ссылки на остальные страницы
						else echo '<a class="page" href="' .base_url . 'metodrecommendations/teacher?page=' . 
							$j . '">' . $j . '</a> &nbsp; ';
					}
				}

        // Выводим ссылки "вперед" и "на последнюю страницу"
				if ($j>$page && ($page+2)<$j) {

    // Чтобы попасть на следующую страницу нужно увеличить $pages на 2
					echo '<a class="page" href="' .base_url . 'metodrecommendations/teacher?page=' . ($page+2) . 
					'"> ></a> &nbsp; ';

    // Так как у нас $j = количество страниц + 1, то теперь 
    // уменьшаем его на единицу и получаем ссылку на последнюю страницу
					echo '<a class="page" href="' .base_url . 'metodrecommendations/teacher?page=' . ($j-1) . 
					'">>></a> &nbsp; </span>';
				}
			}
			?>
		</div>
