<div class="content_left">

    <?php        
    $errorsl = $this->get('errorsl');

    if (!empty($errorsl)) { ?>
    <div class="sidebar_error">
        <span style="color:white;"><?php echo $errorsl; ?></span>
    </div> 
    <?php }
    if (!isset($_SESSION['email'])) {            
        ?>
        <div class="sidebar2">
            <h2>Вхід</h2>
            <form action="<?php echo base_url . 'user/login'; ?>" method="post">
                <input type="text" name="email" value="<?php echo @$_POST['email']; ?>" placeholder=" ваш email" required/>
                <input type="password" name="password" id="pswrd" placeholder=" ваш пароль" required/>
                <input type="submit" name="login" value="увійти" />
            </form>
            <div class="lables">
                <span><a href="#">Забули пароль?</a></span> 
            </div>
        </div>
        <?php }
        else {
            header("Location: /");
        }  ?>

    </div>