<div class="content_left">		
	<?php
	$data = $this->get('data');
	$errors = $this->get('errors');
	
	if (!empty($errors)) { ?>
	<div class="sidebar_error">
		<span style="color:white;"><?php echo $errors; ?></span> 
	</div>
	<?php } ?>
	<div class="sidebar2">
		<h2>Реєстрація</h2>
		<ul>
			<form action="/user/registration" method="post">
			<li>
			<label for="name"></label><br/>
			<input type="text" name="name" id="name" value="<?php echo @$data['name']; ?>" placeholder=" І'мя" required>      <br/></li>
			<li>
			<label for="surname"></label><br/>
			<input type="text" name="surname" id="surname" value="<?php echo @$data['surname']; ?>" placeholder=" Прізвище" required><br/>
			</li>
			<li>
			<label for="patronymic"></label><br/>
			<input type="text" name="patronymic" id="patronymic" value="<?php echo @$data['patronymic']; ?>" placeholder=" По батькові" required><br/><br/>
			</li>
			<li>
			Ваша стать:<br/>
			<label class="radio">
				<input type="radio" name="pol" value="1" >
				<div class="radio__text">Чоловіча</div>
			</label>
			<label class="radio">
				<input type="radio" name="pol" value="0" >
				<div class="radio__text">Жіноча</div> 
			</label>
			<br/>
			</li>
			<li>Дата народження:<br/>
			<select name="day">
				<option >День</option>
				<?php for($i = 01;  $i <= 31; $i++ ): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>

			<select name="month">
				<option>Місяць</option>
				<?php for($i = 01;  $i <= 12; $i++ ): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>

			<select name="year">
				<option>Рік</option>
				<?php for($i = 2018; 1950 <= $i; $i-- ): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>
			</li>
			<li><label for="email"></label><br/>
			<input type="email" name="email" id="email" value="<?php echo @$data['email']; ?>" placeholder=" Ваш email" required><br/></li>
			<li>
			<label for="password"></label><br/>
			<input type="password" name="password" id="password" placeholder=" Ваш пароль" minlength="6" required></li>
			<li>
			<label for="password"></label><br/>
			<input type="password" name="password-confirm" id="password-confirm" placeholder=" Підтвердження пароля" minlength="6" required></li>
		</ul>
		<br/><br/>
			<input type="submit" name="enter" value="Зареєструватися">


		</form>
	</div>	
</div>